### ISSUE TITLE
Always convert font consolas to code

### ISSUE THREAD

**Issue by tbm** [xuhcc/beancount-docs#10]
Maybe I'm wrong but it seems that font "consolas" should always be converted to Markdown code.

For example at https://docs.google.com/document/d/1s0GOZMcrKKCLlP29MD7kHO4L88evrwWdIO0p4EwRBE0/ we have:

> Null objects (NULL)

NULL is in consolas font. And in fact: Null objects (`NULL`) looks better to me.

Is there a reason this is not done? Maybe there's a good reason.

**Comment by xuhcc** [comment]
There's a rule that converts paragraphs in Consolas font to the code blocks.

https://github.com/xuhcc/beancount-docs/blob/a000802f467b3a98af24b39c4113d2617fbec5b3/export.py#L68-L69

Maybe it doesn't work for single words.

**Comment by tbm** [comment]
> Maybe it doesn't work for single words.

Yes, thats what I was trying to say. Sorry for not being clear.

It works for paragraphs.
