### ISSUE TITLE
List split into two

### ISSUE THREAD

**Issue by tbm** [xuhcc/beancount-docs#11]
This list under "Tags" at https://xuhcc.github.io/beancount-docs/24_beancount_design_doc.html (search for "Tags are sets of strings that can be used to group sets of") is split into two lists:

```
<li>All transactions during a particular travel might be tagged to later summarize your trip expenses. Those transactions will usually occur around the same date and therefore there is convenient syntax used to automatically tag many transactions that are declared together in a file.</li>
</ul>
<!-- -->
<ul>
<li>
```

Looking at the Google doc is looks like a single list.  Is this a problem with the conversion or the Google doc?

**Comment by xuhcc** [comment]
I think it's Google doc. I would try to remove newline after `that are declared together in a file.` and then add it again, that trick worked when I faced similar issue on another page.

**Comment by xuhcc** [comment]
Or better, do this with every newline in this list. I just tried this with the exported docx document and it worked, so it will probably fix the original googledoc too.

**Comment by tbm** [comment]
I think I've fixed the Google doc now. Thank you.

But do the instructions from the README actually work:

```
python3 ./export.py document "1N7HDXuNWgLG2PqFS4Kkgv5LzAAtU6c97UVNT7tdTIjA" foo.docx
python3 export.py convert foo.docx foo.md
Traceback (most recent call last):
  File "export.py", line 181, in <module>
    main()
  File "export.py", line 176, in main
    output_fmt=args.format,
  File "export.py", line 126, in convert
    outputfile=output,
  File "/home/tbm/.local/lib/python3.7/site-packages/pypandoc/__init__.py", line 101, in convert_text
    outputfile=outputfile, filters=filters)
  File "/home/tbm/.local/lib/python3.7/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
```

**Comment by xuhcc** [comment]
I'm not seeing this error in my setup. Could you try to install requirements into virtualenv?

**Comment by xuhcc** [comment]
But I can confirm that it was fixed. Thanks!

I pushed an update: https://github.com/xuhcc/beancount-docs/commit/51d3bcb5bf70f7b92c370612581f4cff7e29509e#diff-e335123b756453c8cb7ab223690ab557L475-L476

**Comment by tbm** [comment]
> I'm not seeing this error in my setup. Could you try to install requirements into virtualenv?

Working fine with virtualenv. Sorry for the noise.
