### ISSUE TITLE
Links refer to .md instead of .html

### ISSUE THREAD

**Issue by tbm** [xuhcc/beancount-docs#2]
The link in the footnote at the end of the [intro](https://xuhcc.github.io/beancount-docs/01_command_line_accounting_in_context.html) refers to the `.md` extension instead of `.html`

**Comment by xuhcc** [comment]
I think it is a bug in Github Pages service. Reported it here https://github.community/t5/GitHub-Pages/Internal-links-in-footnotes/m-p/28977/highlight/true#M1977

**Comment by xuhcc** [comment]
I tracked down this bug to [jekyll-relative-links](https://github.com/benbalter/jekyll-relative-links/issues/56) plugin.
Now we use mkdocs generator instead of jekyll, so the problem is gone.
