### ISSUE TITLE
Convert UTF-8 quotes in code elements

### ISSUE THREAD

**Issue by tbm** [xuhcc/beancount-docs#8]
We sometimes see UTF-8 quotes in code elements like

```
YYYY-MM-DD open Account [ConstraintCurrency,...] [“BookingMethod”]
```

Since this is invalid, I am wondering if the conversion should fix that.

(I'll try to fix the Google docs as well.)

**Comment by tbm** [comment]
Also single quotes as in here:

> bean-query myfile.beancount ‘balances from year = 2014’

**Comment by xuhcc** [comment]
Better to change this in the Google doc.
